import type { NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative flex items-center justify-center">
        <p className="absolute left-10 text-2xl text-neutral-100">
          Hello {sessionData ? sessionData?.user?.name : "stranger"}
        </p>
        <div className="text-5xl font-extrabold leading-normal text-neutral-100 md:text-[5rem]">
          FMRL<span className="text-purple-300">Q</span>
        </div>
        <button
          className="absolute right-10 rounded-md border border-neutral-100 px-4 py-2 text-xl shadow-lg hover:bg-neutral-600"
          onClick={sessionData ? () => signOut() : () => signIn()}
        >
          {sessionData ? "Sign out" : "Sign in"}
        </button>
      </div>
      <main className="container mx-auto flex flex-col items-center p-4">
        <div className="flex flex-col gap-10 lg:w-2/3">
          <div className="space-y-2">
            <h1 className="text-xl font-bold ">Ask a question:</h1>
            <input
              placeholder="Write"
              spellCheck="false"
              className=" w-full text-purple-300"
            />
          </div>
          <div className="space-y-2">
            <h1 className="text-xl font-bold">Answer a question:</h1>
            <div className="rounded-lg border border-dashed border-neutral-600 p-5 text-center text-2xl font-bold text-purple-300">
              What is the meaning of life?
            </div>
            <textarea placeholder="Answer" className="min-h-[10rem] w-full" />
          </div>
          <button
            className="rounded-md border border-neutral-100 px-4 py-2 text-xl shadow-lg hover:bg-neutral-600"
            onClick={() => console.log("clicked")}
          >
            Proceed!
          </button>
        </div>
      </main>
    </>
  );
};

export default Home;
